version: '2'
services:
  toga:
    build:
      context: .
      dockerfile: ./DockerfileDev
    image: toga-dev
    ports:
      - 8080:8080
    links:
      - redis
    command: npm run test
  redis:
    image: redis
