version: '2'
services:
  toga:
    build:
      context: .
      dockerfile: ./DockerfileDev
    image: toga-dev
    ports:
      - 8080:8080
      - 3001:3001
    volumes:
      - ./app:/service/toga/app
      - ./components:/service/toga/components
      - ./script:/service/toga/script
    links:
      - redis
  redis:
    image: redis
